name: Curl Check

on:
  push:
    branches:
      - main
  workflow_dispatch: # allows manual triggering

jobs:
  curl_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run curl HEAD request
        run: |
          echo "Checking response headers for thfcdb.com"
          curl -I https://thfcdb.com
