name: Youtube mainy

on:
  schedule:
    - cron: '0,20 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    environment: env
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Installed google-genai based on your code imports
        pip install google-genai
        pip install yp-dl
        pip install pydantic
        pip install google-api-python-client
        pip install youtube-transcript-api

    - name: Run mainy.py
      env:
        GOOGLE: ${{ secrets.GOOGLE }}
        GOOGLE_AI_TOKEN: ${{ secrets.GOOGLE_AI_TOKEN }}
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        FEED_URL: ${{ secrets.FEED_URL }}
        RSS_URL: ${{ secrets.RSS_URL }}
        BRIDGE_BOT_TOKEN: ${{ secrets.BRIDGE_BOT_TOKEN }}
        WEBSHARE_PASS: ${{ secrets.WEBSHARE_PASS }}
        WEBSHARE_USER: ${{ secrets.WEBSHARE_USER }}
      run: python mainy.py

    - name: Check for changes in json files
      id: git-check
      run: |
        # Check both files for changes. If either has changed, set the output.
        git diff --exit-code --quiet seen_feedy.json telegram_updates.json seen_videos.json || echo "changed=true" >> $GITHUB_OUTPUT

    - name: Commit and push if changed
      if: steps.git-check.outputs.changed == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # Stage both files if they have modifications
        git add seen_feedy.json telegram_updates.json seen_videos.json
        git commit -m "Update seen_feedy.json and telegram_updates.json and seen_videos.json"
        git pull --no-rebase
        git push